apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: |
           MIIEkDCCA3igAwIBAgIUH6ttOP1pby6TxAkdVwCbXZAxga8wDQYJKoZIhvcNAQEL
           BQAwgYExFDASBgNVBAYTC05ldGhlcmxhbmRzMRYwFAYDVQQIEw1Ob29yZC1Ib2xs
           YW5kMRIwEAYDVQQHEwlBbXN0ZXJkYW0xCzAJBgNVBAoTAlZVMRswGQYDVQQLExJG
           YWN1bHR5IG9mIFNjaWVuY2UxEzARBgNVBAMTCmt1YmVybmV0ZXMwHhcNMjIwMjA2
           MDkyOTAwWhcNMjMwMjA2MDkyOTAwWjCBgTEUMBIGA1UEBhMLTmV0aGVybGFuZHMx
           FjAUBgNVBAgTDU5vb3JkLUhvbGxhbmQxEjAQBgNVBAcTCUFtc3RlcmRhbTELMAkG
           A1UEChMCVlUxGzAZBgNVBAsTEkZhY3VsdHkgb2YgU2NpZW5jZTETMBEGA1UEAxMK
           a3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOIl5XhB
           HD5kX1TKXKnswdi2+piV6mO+yCAEhWIvR5gfHAXcbiax/pihCXGyexWi/fzKQqo1
           Fz5K/twwlMpI4wqIZjjPdR7IdaSNC2rmnFDbPYb6BpptRmhRIGw6Z8JYyFH33SeQ
           QES57bdPsKaEV9JJ3GG2k8L48dzSukr+TbnEg9/D8QZWbyvjSIwQK9Ofn0cX+3aP
           ldLo4CFm51OWXssjUqN15t1j4QLbQgU4pcvhxy8PTPmrCOdtqRJ3Bhmtf9Y1kMPm
           J6I10PGDHAcIMur5E+fF+vqk7XL4WJKuxjKdSxZtXEpp8dMlIFVEOKhRPzV4+0r8
           5V6yGddoSfuIga8CAwEAAaOB/TCB+jAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
           FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFDZ/
           rR4R5t2N4I2KC6Xm7YDKKnaXMIGbBgNVHREEgZMwgZCCCmt1YmVybmV0ZXOCEmt1
           YmVybmV0ZXMuZGVmYXVsdIIWa3ViZXJuZXRlcy5kZWZhdWx0LnN2Y4Iea3ViZXJu
           ZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVygiRrdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
           LmNsdXN0ZXIubG9jYWyHBH8AAAGHBAqYtwGHBAqYtwEwDQYJKoZIhvcNAQELBQAD
           ggEBAH/7+M9Lp64jkjeXUaocsrMrTvTIoP6bdpcJv2F9lEKwzc+cxBw/OMKYjfIf
           NBpH4bWz2SOnGePkS6MsCeKg9dOHAnG16hKf6D4IHP6R/1nRhssGv/sBkm/Asp25
           gwljF/hahiTirdBI93vuo1qCJtJXBi0JaaM7cMB4AMrtH+y1yuHcjMGrKI2evDyJ
           Jskzib3K+TZe4ROjLT3WodjwwPeYs8g/qyEgmd0PDpBXnAo4M61roXRMHIqBMvqD
           onZcQHI67YzY7fGdKn/5BUvSjCgRegaHs89+TwlOMhP1IJP8Uf3TIcOJk3pvWSnm
           kV1h2+vMWYaPyqN30+7+aSgRX8Q=
 
  tls.key: |
           MIIEpgIBAAKCAQEA4iXleEEcPmRfVMpcqezB2Lb6mJXqY77IIASFYi9HmB8cBdxu
           JrH+mKEJcbJ7FaL9/MpCqjUXPkr+3DCUykjjCohmOM91Hsh1pI0LauacUNs9hvoG
           mm1GaFEgbDpnwljIUffdJ5BARLntt0+wpoRX0kncYbaTwvjx3NK6Sv5NucSD38Px
           BlZvK+NIjBAr05+fRxf7do+V0ujgIWbnU5ZeyyNSo3Xm3WPhAttCBTily+HHLw9M
           +asI522pEncGGa1/1jWQw+YnojXQ8YMcBwgy6vkT58X6+qTtcvhYkq7GMp1LFm1c
           Smnx0yUgVUQ4qFE/NXj7SvzlXrIZ12hJ+4iBrwIDAQABAoIBAQCk/AjBBp9YVVnH
           PisEPRnexP9lullZk6Hk2eeFjgCpVmjXTc1+pXScXT/Klu99BYBOoDCqhDkE1SnB
           8h9axHn/ASuyXoePgadx+QRPZRa9VnU4t8eBeh9Xk3gX/TQdcTATvMS3TGHWwd5P
           UfAKS5rWa9Q/5Tc/kubAt2v5sjV6RChCSBVl7pO3C7mUhUPYk5xfrnUcHSUrQqcl
           P7Filf8GbA8l+Yr31pPZdl/9s9+j2kauqOf0OtFon//DpUMkLEHy2pEn1VAJ0Ipm
           TxmaYswJaIHT/U7cbdGa452DZbYtHPvAi25gcHFgG8QRHcQeh3hrBzdDTetPD2Vz
           4T3+iUuhAoGBAP/te9Ap4tb3o+kX13G8XP8ey/KA4ItRtZK6kJmkC/SiQ0sGI3YO
           e+jbZnqhmr6tkeJy7UTqmOgY5X1u7bngy6y0S+QWlkNFmmKPSJ5jV2hH7wtVrslV
           Jgo2uu2xQBykEPOhNm4RAcjVqjV18sKJVyAngxviWncYc0k8W9XzHeHzAoGBAOI2
           Qhcl+ht2Jr1d/yfNKNsJgVwQ75ByH6ZejgyQrolyrwpH4pLPtjKJiP0q1ypOQUX8
           R5rNtkhIHCPSzHJ8sTe74N867lDdtQCP97ZdnH8Y5S20mS5hulo0RCPuPnGZlSO0
           qCBXWr5D5NMdrOKIi3FY9yq4Nux7Fq0fB02XFJRVAoGBAO7eyM5NGgVMlDduYk8s
           4ZvZMcBBW9ONSy0NZwOQIvyNKsPukdCRykNX7HmPNnC8bkpuvFizok4XVrNRgx8X
           2uJyUdcs4ckeQO+3Dq+Oxzl00n/A1GfkSqID3UsXQmC5HX1XvgbTZtf93WUSlqfO
           Kny/hFbVWVyJfKkhZhH2XbDTAoGBAMhbAkJ6coFsLne/D0VzYuJOEvM2VNj9G6dB
           TFM4uj4nA335mWYq7tboFhsVnKlt0kZoYgtsdCylIbdg94/XfSc+Erfk/DtHgw9S
           dDZjxz6TEDlhIeOAz4shi9C/LTN0sjGDyv2KIWcvvzZ1rDCge9ES2ShPLOZbRwRi
           3RcN3z5ZAoGBAO/msIBP8DR00BNEQUnPj9dGgG0SBH+8M1eDfa6grTPNSmokd5TQ
           u3lE+/IjS3JhVby10J04FWaR8nd5X+wQCgR1dWdObodoB977CPpJLa1rGWaQAU3L
           NRG4XGOeEwUEAqQEjpYibOqzz0RB/OS6hcU6dPfsc6vwzi2gRHA+K5Ha
